### ISSUE TITLE
Only a white screen when not connected to the internet

### ISSUE THREAD

**Issue by probonopd** [eNkru/freelook#12]
Shows only a white screen when not connected to the internet:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/72f6ba06e9800e0268bb12bd6515fd4ccb565c28/database/Freelook/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/1299

**Comment by eNkru** [comment]
@probonopd finally got sometime to solve this :)

https://github.com/eNkru/freelook/releases/tag/v1.0.0
