### ISSUE TITLE
Snap package support [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [eNkru/freelook#13]
I was wondering if you might have an interest in making [snap package](https://snapcraft.io/) version. Also, your app would be promoted on the [snap store page](https://snapcraft.io/store).

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by eNkru** [comment]
will find sometime to have a look. see if can be added into snap. Pull request also welcomed :)

**Comment by 0lzi** [comment]
https://github.com/julian-alarcon/prospect-mail

This appears to be a renamed fork of this project and is available in the snapstore : [Prospect Mail](https://snapcraft.io/prospect-mail)

**Comment by mikeroyal** [comment]
okay cool.
