### ISSUE TITLE
support on-premise outlook deployment

### ISSUE THREAD

**Issue by kundeng** [eNkru/freelook#16]
Can this be adapted to support on-premise outlook deployment?

**Comment by eNkru** [comment]
This app is a wrapper to the offical online application. is your on-premise outlook have the online version looks similar to outlook.com or office.com?

**Comment by kundeng** [comment]
yes, it looks very similar.  However,  it will perform an authentication redirect using our own AD/ldap.  I tried with your app,  once the authentication redirect is done, it comes back to microsoft login prompt and becomes a loop.

**Comment by eNkru** [comment]
We are using office.com as our company email, we authenticate with our AD and do a redirect after that. all looks good.

if you could run this app with the dev mode. check if any error in the terminal console or the DevTools console. 
You can press F12 to pop up the DevTools once running in dev mode. 

Electron is using chromium as the core browser, shouldn't have any different with a real chrome.

Just have a look if any error cause the authentication failed.

**Comment by eNkru** [comment]
are you trying to login your on-premise email account with the login page in the app?

The login in the app is either for outlook.com or office.com, if your email server is private. You can't login with that page, because it's not your on-premise login window :)

Let me know the answer, I have a plan to allow user to customise the home page to what ever meaningful.

**Comment by kundeng** [comment]
yes to on-premise outlook.   Please provide an option so that one can start with on-premise URI .

**Comment by eNkru** [comment]
just wondering what's the url looks like? Also I am worrying about once open the input for the url, this will become a desktop shell for any web app :)

**Comment by hovancik** [comment]
web access is like: example.com/owa

**Comment by eNkru** [comment]
There is a workaround solve this issue.

https://github.com/eNkru/freelook/issues/17#issuecomment-621684063

But I am not going to include this in the release app as it stores the clear text credentials in local computer. Feel free to do this as far as you have your protection for your own computer.
