### ISSUE TITLE
[request] offline support

### ISSUE THREAD

**Issue by fla15** [eNkru/freelook#20]
it's more helpful if we can using on the offline mod

**Comment by eNkru** [comment]
It's quite difficult to implement the offline mode without the official support. To handle the data retrieved and stored local is not the goal of this project. Actually I started this project to avoid to store the confidential data to my local computer :)

If you are keen to keep the downloaded emails, I'd suggest to use one of the email client, such as evolution or thunderbird. they both support the POP3 or IMAP protocols. The evolution is the one come with EWS plugin to allow you connect to the office365 and your enterprise email service.
