### ISSUE TITLE
AppImage don't working

### ISSUE THREAD

**Issue by fla15** [eNkru/freelook#21]
showing up just one sec in taskbar
tested with [appimagelauncher](https://github.com/TheAssassin/AppImageLauncher) and [libappimage](https://appimage.org/)
Manjaro KDE 4.19.66-1-MANJARO 
KDE Plasma 5.16.4

**Comment by eNkru** [comment]
I don't have the KDE environment. Just googled your issue and get the following. Looks like a electron.js issue with KDE Plasma.

See if you could solve it with the suggested answer.

https://github.com/electron/electron/issues/18261
https://www.reddit.com/r/kde/comments/aiafsr/global_menu_dont_work_only_in_one_specific/
https://forum.manjaro.org/t/solved-electron-global-menu-is-not-working-on-plasma/44640/3

**Comment by eNkru** [comment]
could you try this new release

https://github.com/eNkru/freelook/releases/tag/v1.0.1
