### ISSUE TITLE
No spell checker :-(

### ISSUE THREAD

**Issue by dcioccarelli** [eNkru/freelook#26]
It would be nice to have a spell checker integrated into the app. Kind of important with an e-mail client. See: https://www.npmjs.com/package/electron-spellchecker

**Comment by eNkru** [comment]
Thanks for the advice :) I'll have a look see if it's possible to integrate the tools in.

**Comment by eNkru** [comment]
@dcioccarelli thanks for this suggestion. 

it's been implemented [here](https://github.com/eNkru/freelook/commit/db74e3d485992c720e42fcac89b0585012ebb048)

**Comment by eNkru** [comment]
The spell checker is enabled 5 seconds after the window loaded. Assume you won't write anything in the first 5 seconds :)

**Comment by dcioccarelli** [comment]
Excellent! Working as expected. Thanks a lot!

**Comment by eev2** [comment]
Hi. That's great but do you plan to add other languages or only US English?

**Comment by eNkru** [comment]
> Hi. That's great but do you plan to add other languages or only US English?

Other languages can be supported. This is just a quick add for the request. Need to think how to configure the language, maybe in settings. The spellchecker can automatically detect the type in language and switch on the fly, but setting the default language has much better result.

What language do you need to support? I'd like to get a list.

**Comment by eev2** [comment]
Cool, thanks. I think having the option would greatly benefit the software. I write mainly in UK English and sometimes in Greek, but I'm sure you will find people who write with different languages.

**Comment by doki-nordic** [comment]
Spell checker suggestions from context menu did not work for me. I fixed it in my fork. See last commit in following branch:

https://github.com/doki-nordic/freelook/commits/spell-check-menu-fix
