### ISSUE TITLE
Can we get other office apps this way?

### ISSUE THREAD

**Issue by suoko** [eNkru/freelook#27]
According to a MS Dev, most desktop apps of office suite are actually electron apps compiled for each os ( https://mobile.twitter.com/TheLarkInn/status/1006761134395834368 ).
Would it be just a question of a 'npm build dist' to have desktop apps for all?

**Comment by eNkru** [comment]
There is no such magic to convert the web application to a electron native app. You have to do some of the logic to load the web version into your electron app.

However, there is a way (actually I believe some apps already did) is just do a simple wrapper to the web application into the native app. so you are running the webpage inside your app.

It's not hard to do this. However when you try to integrate the notifications, or some customised function, every web application are different.

This app is focus on the `hotmail.com` and the `outlook.com`, provide some extra desktop app functions to help the productivity.

I am not using all of them, so just convert the hotmail.com I am using daily to an election app. It's pretty simple to wrap other web applications into electron though :)

**Comment by suoko** [comment]
> It's not hard to do this. However when you try to integrate the notifications, or some customised function, every web application are different.


Other office apps (Excel, PowerPoint and word) do not care about notifications, the only custom function I can think of is file saving to local drive.
They could be ported (at least the 32bit versions) very very easily.
I'm not saying you should do it, but some body else at MS

**Comment by eNkru** [comment]
Yes, it's pretty easy to shell a web application into electrion app.
