### ISSUE TITLE
[Feature Request] Handle mailto links

### ISSUE THREAD

**Issue by ajgringo619** [eNkru/freelook#28]
I can set the app as my default mail program, but clicking on an email link just switches to the program (or opens it if necessary). Can this be added?

**Comment by eNkru** [comment]
If you'd like the freelook work as the default email client and open the compose page when you click mailto: links in website. To be honest, I am not quite sure how to do it from the Elelctrion.js apps :(

Anyone see other election app did the trick, please point me the example. I might able to figure out the magic :)

**Comment by ajgringo619** [comment]
Thanks for the quick response! This is the first Linux email client that I've ever used that works flawlessly with Outlook; even their website (was using it before I found this project) would never last more than 24 hours without a hard crash, regardless of the browser.

**Comment by eNkru** [comment]
thank you for the feedbacks which motivate me for this app :)
