### ISSUE TITLE
Can't make any settings changes

### ISSUE THREAD

**Issue by ajgringo619** [eNkru/freelook#29]
(Linux Mint 19.3 XFCE)
When I click on the tray icon, then select **Settings**, I cannot change any of the ad blocking values. I wanted to test the app without any ad blockers as I'm subscribed to Office 365 and don't get ads anymore anyways.

**Comment by eNkru** [comment]
Normally you can just click to focus t he text input and typing something in it.

What's your setting UI looks like? could you share a screenshot?

I've attached my one.
![image](https://user-images.githubusercontent.com/13460738/83981910-58d7e380-a976-11ea-912b-31e4087c8ecd.png)

**Comment by ajgringo619** [comment]
I can select one of the settings, but I can't change any of the data.

![image](https://user-images.githubusercontent.com/53413561/83982087-6fc7f880-a8d8-11ea-9e09-ee79f5ff75e1.png)

**Comment by eNkru** [comment]
those are default values. what if you just click to select and start typing?

**Comment by ajgringo619** [comment]
Nothing happens. I can't even highlight the text to cut/paste.

**Comment by eNkru** [comment]
That's weird. Could you change the Home URL on the bottom? it's a dropdown(up) list contains two options.

Another question is, are you build your own package?

**Comment by ajgringo619** [comment]
Yes, I can change the home URL (at least the option is available).
No, I used the available deb.

**Comment by eNkru** [comment]
That package is built a year ago. Do you keen to try this one

https://file.io/X1Ja2cqH

Let me know if you have the same problem

**Comment by ajgringo619** [comment]
Link doesn't work (404- file not found).

**Comment by eNkru** [comment]
> Link doesn't work (404- file not found).

https://we.tl/t-0DYye2xYD9

try this one instead

**Comment by ajgringo619** [comment]
That did the trick - thanks! I changed all of the ads settings to a single space (it would not allow an empty entry) and it works just fine.

**Comment by eNkru** [comment]
Thank you for the feedback. I reckon your previous issue is due to some old version, it's been year ago for the last release.

I might release a new version soon.

**Comment by eNkru** [comment]
https://github.com/eNkru/freelook/releases/tag/v1.0.1

The updated package also available in the new release 1.0.1
