### ISSUE TITLE
Window Stuck on Task Screen

### ISSUE THREAD

**Issue by ajgringo619** [eNkru/freelook#31]
(Linux Mint 19.3, Freelook v1.01)
I accidently clicked on a task pop-up, took me to the edit screen of the task. I became stuck (in a maximized window), no way to go back to the original mail/calendar window. I exited the program, restarted, and was right back to the task window - again, stuck. After purging $HOME/.config/Freelook I was able to get back in.

I don't know if this issue existed in previous versions as I usually use my phone's **Microsoft To-Do** app to manage tasks.

**Comment by eNkru** [comment]
I've noticed MS has some popup has no close button. such as when you double click the email, it will open in a fullscreen of that email and no UI to back to the list. For this instance I have to restart the app to bring it back :(

For the task pop up I reckon it's similar happens. I'll see if I could open a new window for popups. so at least it won't overwrite the window.

**Comment by eNkru** [comment]
@ajgringo619, I've removed the logic to load the popup in same window. It should open a new window for those sort of things. But I couldn't find the example to verify. Could you reopen this issue if you still having the issue? Also be good if you can verify it's been fixed.
