### ISSUE TITLE
App always launches into the home page without signing in.

### ISSUE THREAD

**Issue by jackiecorn** [eNkru/freelook#34]
I have launched the app and signed in with no problem.
However when I quit the app and launch it again it doesn't automatically go to the logged in Inbox page, but instead shows the home page so I need to click Sign in again.

I'd like it to open the logged in page right away please.

**Comment by jackiecorn** [comment]
I've fixed it by changing all references of "https://outlook.live.com/" to "https://outlook.office.com/"
As well as clearing user data and signing in again.
I guess I can close this issue.

**Comment by eNkru** [comment]
outlook.live.com is for some old hotmail account which I am using at the moment. there is a option in setting you can pick to use live or office :)

**Comment by jackiecorn** [comment]
Yep. Just found the setting for that.
I was looking hard for where the settings were and finally it in the system tray icon on mac.
Wish it was better explained in the readme though.
Thanks!
