### ISSUE TITLE
Login not persistent

### ISSUE THREAD

**Issue by karthick-kk** [eNkru/freelook#36]
Login is not persistent across reboot. I have to re-login every time open the app.

**Comment by eNkru** [comment]
electron.js is using local storage to save the user data for the embedded chromium. It should work unless you have issues to store data in your local.

Freelook is using the default location, if you are on linux check if the following folder exists

`~/.config/Freelook`

The following article explains how the electron app store user data

https://medium.com/cameron-nokes/how-to-store-user-data-in-electron-3ba6bf66bc1e

**Comment by karthick-kk** [comment]
I can see the files are getting created and updated. 

![image](https://user-images.githubusercontent.com/1493364/90363445-64cfd800-e080-11ea-977c-0fbb90187629.png)

**Comment by sect2k** [comment]
@karthick-kk had the same or similar issue, login would not persist. What resolved it was changing default "home" in settings to "outlook.office.com", since I have a Outlook365 (work) account.

It's been working fine since. Hope this helps.

**Comment by luisrdzruiz** [comment]
Same issue for me.

SO> Fedora 32
Freelook Version> 1.0.1

**Comment by eNkru** [comment]
> Same issue for me.
> 
> SO> Fedora 32
> Freelook Version> 1.0.1

are you using outlook.office.com or outlook.live.com?

check if sect2k's suggestion fix for you

**Comment by sspade1** [comment]
Is there a setting to change to get this in ~/.config/Freelook/Settings or ~/.config/Freelook/Preferences ?
I still have "homepageUrl":"https://outlook.live.com/mail" in ~/.config/Freelook/Settings with using regular outlook.com

**Comment by caseyjhol** [comment]
> @karthick-kk had the same or similar issue, login would not persist. What resolved it was changing default "home" in settings to "outlook.office.com", since I have a Outlook365 (work) account.
> 
> It's been working fine since. Hope this helps.

Can confirm this worked for me (with a work account).

```bash
sudo nano ~/.config/Freelook/Settings
```

**Comment by eNkru** [comment]
I reckon it's been solved. Reopen it if still have the issue
