### ISSUE TITLE
Problem do Login in Work account

### ISSUE THREAD

**Issue by Colmanetti** [eNkru/freelook#43]
Hello , 

My organization have a redirect to insert a username / password of yours intranet. But the app dont ask for it, like the browser . Anyone has any ideas how to resolve this ? And just go to blank white screen

**Comment by eNkru** [comment]
Any screenshot? I remembered we've got this request long times ago, and it's been solved. I'd like to see more in details.

**Comment by aegagros** [comment]
I have the same issue; no screenshot to post other than a blank white screen. It may be a proxy issue on my case. Any way to manually/explicitly specify a connection proxy?

**Comment by eNkru** [comment]
@aegagros no proxy setting at this stage. I'll have a look to add the proxy support

**Comment by jhakonen** [comment]
@Colmanetti and @aegagros can you try my PR #48, see if that would help you.

**Comment by Colmanetti** [comment]
@jhakonen I resolve my problem . I will make a PR with my solution

**Comment by Colmanetti** [comment]
@jhakonen It`s works perfectly. I test , and pop up an new window to put username and password for SSO. 

@aegagros  You can try , i think u dont need proxy support.

**Comment by aegagros** [comment]
I tried to build from your repo but it fails; could it be because I have node v10.19.0 in ubuntu 20.04? I am not very familiar with node development tbh, and its a company pc which I have very little update capabilities.

In any case, I will monitor this PR until merged, and will use the prebuilt deb package. Thanks for that!

**Comment by jhakonen** [comment]
Yeah, node v10 will not cut it, even running `npm i` fails to error `Error: Cannot find module 'fs/promises'`.
You'll need to use node v14 or newer. 

I think you can install newer version using these instructions:
https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

Personally, I'm using nvm (https://github.com/nvm-sh/nvm) to switch between node versions, but that may be overkill for your needs.
