### ISSUE TITLE
Creating a Meeting/Event directs me to browser

### ISSUE THREAD

**Issue by rollno748** [eNkru/freelook#61]
Creating a new Meeting/Event directs me to browser and not within the app.

OS: Ubuntu 
version: 20
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               GenuineIntel
  Model name:            11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    CPU family:          6
    Model:               140
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            1

**Comment by eNkru** [comment]
MS Outlook re-design their new UI will pop up a window to create an event if you are on mail page. The app will try to open a new web browser window as the current behaviour. I'll see if we could catch that request and open in the app.
